### ISSUE TITLE
Why current_move_is_historic() must be a getter property?

### ISSUE THREAD

**Issue by PedanticHacker** [PedanticHacker/ChessFighter#11]
There's a thing in the codebase I want to understand. It's about

    ChessFighter/source/game.py
    Line 97, 98
    @property
    def current_move_is_historic(self):

I just don't understand why do we need to define the method `current_move_is_historic()` as a getter property of the `GameState` class in the `game` module. @mfitzp, can you elaborate on this? If the method is not defined as a getter property, a crash occurs when called in the `window` module. I really want to understand why this getter property is so crucial.

**Comment by mfitzp** [comment]
The `@property` just means that it is accessible via `game.current_move_is_historic` rather than calling it as a method, i.e. `game.current_move_is_historic()` ...it has no effect on the behaviour of the method. The reason it will crash without that, is that if you don't define it as a property, `game.current_move_is_historic` will actually return the method object, not the result of the method. If you remove the `@property` decorator you need to also change all access to it to use `game.current_move_is_historic()`

Why use a property? It's a style thing. The method is a simple method which doesn't affect anything, takes no arguments and returns a simple value (boolean). It is telling you something about the current state of the game object, making it conceptually similar to an object property. 

Using property methods is preferable to creating a lot of state variables (which can be difficult to keep in sync, and clutter things up)  -- although you can only do this where you have the necessary state information to calculate the value.

**Comment by PedanticHacker** [comment]
Ah, now I understand! Thanks for clarifying this, I learned one new thing today. You are amazing!
