### ISSUE TITLE
Any benefit in incorporating QThreadPool + QRunnable?

### ISSUE THREAD

**Issue by PedanticHacker** [PedanticHacker/ChessFighter#12]
This is a question I am asking myself for a long time now. Currently, a `QThread` is used to handle the chess engine's long-running process to not block the PyQt's main GUI event loop. It works fine.

But since the Chess Fighter's default chess engine Stockfish 12 has an option to increase the number of threads to do its thinking, having just one `QThread` to handle all those chess engine threads, I don't think we are utilizing it to its fullest potencial. I have a 4-core and thus 8-thread AMD Ryzen 5 processor. Having only one `QThread` instance in which the chess engine operates is a huge restriction. I think the `QThreadPool` would/could manage all those threads for us.

So my question is: **Should we toss `QThread` and upgrade to `QThreadPool + QRunnable`?**
(If yes, we should subclass `QObject` to use the signals & slots mechanism since `QRunnable` doesn't support it.)

Is this something that would/could increase the capability of the chess engine? Is there anything better? Maybe `asyncio + quamash` is the answer? Or maybe `asyncio + asyncqt`?

**Comment by mfitzp** [comment]
I don't think this would improve the performance of the engine. A couple of things --

There isn't any difference between running this on a `QThread` and as `QRunnable` -- in both cases you would only have it executed as many times as you start it (once). 

`QThreadPool` is a "pool of threads" which you can borrow threads from. When you create a thread pool, you tell it how many threads it should have, and then pass it things (`QRunner` objects) to execute. The threadpool takes these runners, matches them up with a spare thread, and executes the runner on the thread. 

That means it doesn't do anything magical to make your code more concurrent, or run it multiple times. You *can* create multiple `QRunners` just as you can create multiple `QThreads`, but each execution is independent. The only advantage of using pools is that you don't need to manage the individual threads yourself (starting, stopping, etc.) and you can define a maximum number of concurrent threads (to optimise performance).

But ...none of this really matters in this case, as to change the number of threads used by the engine you need to look somewhere else. The key thing to know is that a thread can spawn other threads and processes -- the main Python thread spawns your `QThread` which spawns the stockfish process, which spawns it's own threads. So the performance of the engine is independent of how you handle the threads in your own program.

For improving the performance of the engine I think you need to edit this configuration here.

```python
            engine_options = dict(
                Threads=4,
                Hash=4096,
                EvalFile=nnue_file
            )
```

-- I think(!) the `Threads` parameter here can be anything you like. If you want to scale to the host you're running on, take a look at `QThreadPool.maxThreadCount()`. This does a calculation based on your CPU to determine the most efficient number of threads to use... it's probably a bit conservative, given it's based on long-term maxing out, but you can use it as a basis. 

I'm entertained by the idea of making the engine better, since I've still not beat it once! :D

**Comment by PedanticHacker** [comment]
Thanks for this awesome explanation!

`QThreadPool().maxThreadCount()` returns `8` on my computer. There's also `os.cpu_count()` that does the job. You're right, and I think it's best not to hard-code things like that.

Do you happen to know which Python's "batteries included" function returns the amount of RAM memory?

**Comment by PedanticHacker** [comment]
[728731b](https://github.com/PedanticHacker/ChessFighter/commit/74c5d54719b01764df8491aad9ae22fdfebd19d6) fixes the hard-coded number of threads in the engine options.

**Comment by mfitzp** [comment]
Worth mentioning .... as you found "maxThreadCount" is really just calculating based on the number of "cpus" (virtual/effective) that your PC has. It's worth mentioning that this often is a very, very, conservative idea of what "max threads" should be. It only really applies if the work you are doing is cpu-bound -- that is, you're using the cpu to it's max capacity, rather than IO bound, where you're waiting on external data (think network requests, etc.). In that case, your threads are sitting around doing nothing for a lot of the time, so you can comfortably add (lots) more.

In this case (the stockfish algo) it *is* cpu bound, so the value given will probably be about right. If you have more threads, those threads will just compete with each other for CPU time.  Make sense?

For memory, [psutil](https://psutil.readthedocs.io/en/latest/) is what I would look at.

**Comment by PedanticHacker** [comment]
Aha, thanks for the insightful explanation!

Yeah, `psutil` is great! It has this `virtual_memory()` named tuple to get RAM memory info. I just wanted to avoid another 3rd-party library dependency.
