### ISSUE TITLE
The current data structure used for chessboard states is bad

### ISSUE THREAD

**Issue by PedanticHacker** [PedanticHacker/ChessFighter#14]
As @niklasf (Niklas Fiekas), the author of python-chess, upon which this codebase relies heavily, has stated:

**From reading your code it looks like you are creating boards with inconsistent state and history, i.e., the move stack does not match the position. I'd recommend not using internals like _board_state() and restore() at all, as I have done before: [#616 (comment)](https://github.com/niklasf/python-chess/issues/616#issuecomment-682484075), [#618 (comment)](https://github.com/niklasf/python-chess/issues/618#issuecomment-688492849).**

@mfitzp, I think we should use a better data structure for our chessboard states. Any thoughts on this?

**Comment by mfitzp** [comment]
@PedanticHacker  I'm not sure what to suggest here. The `Game` class doesn't have any other way to get the current board state than via `_board_state` and we need to store historic board states in order to display them, as the user clicks back through the list. Can you see another way to store a snapshot of the board?

I don't follow the comment re: boards with inconsistent state/history. The state of the board isn't affected by this historic log (in `self.history` -- that is only used for display, temporarily, as the user clicks/scrolls back up the list. 

The move is only applied when the user makes a new move from that earlier position, in the method `truncate_to_current_move`, which resets the board (correctly, afaik) by using `.pop()` to return to the earlier state. We don't alter the internal state of the `Game` object, so I don't see how we would end up inconsistent.

If we want to get rid of these independent snapshots of the game state (?) we would need clicking back in the historic move list to immediately truncate the board state & moves -- you can roll back to look, but you can't change your mind.

**Comment by PedanticHacker** [comment]
Yeah, you're totally right! I just posted what Niklas Fiekas told me on his python-chess repo. He suggests to use `chess.pgn.Game()` as a data structure, and not `chess._BoardState` objects, so he basically suggests to use `GameNode` objects.

I told him that `GameNode` objects don't expose a `restore()`-like method. So I'm waiting to see if he responds with a useful information regarding this.

But he did told me how to get the chessboard position of an `n`-th node:

```
import chess.pgn

# How to append moves to a game.
game = chess.pgn.Game()
node = game
node = node.add_variation(chess.Move.from_uci("e2e4"))
node = node.add_variation(chess.Move.from_uci("e7e5"))
node = node.add_variation(chess.Move.from_uci("g1f3"))
node = node.add_variation(chess.Move.from_uci("b8c6"))

# How to get the chessboard position of the n-th node.
n = 3
node = game
for _ in range(n):
    node = node.variations[0]
print(node.board())

# You can also easily use your own list of moves.
```

I don't see a way we can incorporate this into our own codebase, @mfitzp. Got any ideas?

**Comment by PedanticHacker** [comment]
Also, Niklas Fiekas told me [this](https://github.com/niklasf/python-chess/issues/643#issuecomment-699209862).

**Comment by PedanticHacker** [comment]
@mfitzp?

**Comment by mfitzp** [comment]
Hey @PedanticHacker I had a look at this this evening and it's certainly non-obvious. Initial work in https://github.com/PedanticHacker/ChessFighter/tree/variants ...it's not working yet, but I'll have another poke tomorrow.

The problem comes with finding historic states, particularly for the table of past moves -- currently we have a static list to store these, while the code above would be iterating down the linked lists for each cell. I'm attempting a mix of both.

**Comment by PedanticHacker** [comment]
python-chess has an update to version 1.1.0. It would be good you update to that version. It has a lot of good code.

Anyway, I was thinking we could also do a snapshot of the chess.Board() instance with its copy() method. So like after a move is pushed, we then make a snapshot of the board and store that snaphot in a list. What do you think?

**Comment by mfitzp** [comment]
That's what we're currently doing though, right? https://github.com/PedanticHacker/ChessFighter/blob/master/source/game.py#L47 ...I think the problem was the use of the private `board_state = self.board._board_state()` ...if there is a public method for that now, then I think it's solved.

**Comment by PedanticHacker** [comment]
Well, not entirely solved. We need something that replaces the `restore()` method, but that method does not exist in the `chess.Board()` class, it only exists in the `_BoardState()` class.

https://github.com/PedanticHacker/ChessFighter/blob/38c00c05d1323200ae5e35ddb2b276052be324e3/source/window.py#L247

So instead of this line of code, we need something else.

**Comment by PedanticHacker** [comment]
To create a snapshot of a board's state, the `copy()` method of `chess.Board()` provides this functionality.

But this only partially fixes the problem of restoring the board's state. Those snapshots are there, but there's no method yet to restore the board from a snapshot that's in the `history` list, either by clicking a moves table item or scrolling the mouse wheel.

**Comment by PedanticHacker** [comment]
The current master produces this error when a new move is added that overwrites a historic move:
```
Traceback (most recent call last):
  File "C:\Users\Boštjan\Desktop\Chess Fighter\source\model.py", line 37, in data
    return game.san_moves[converted_index]
IndexError: list index out of range
```
What have I missed?

**Comment by PedanticHacker** [comment]
@mfitzp?

**Comment by mfitzp** [comment]
The issue is in the model you're pulling data from the `game.san_moves` directly e.g.

```
        if role == Qt.DisplayRole:
            return game.san_moves[converted_index]
```

...but others are using `self._moves` which is the model's internal move representation. A model can only use a single data source, otherwise the `rowCount` and where you attempt to get data from won't match up.

If you change that back to `self._moves` you can pass `game.san_moves` as the data source, e.g.

```
self.moves_model = MovesTableModel(game.san_moves)
```

Once everything in the model is using that same list, things should work as expected.

**Comment by PedanticHacker** [comment]
I fixed the line `216` in `source/window.py` to `self.moves_model = MovesTableModel(game.san_moves)` and now the error is this:

```
Traceback (most recent call last):
  File "C:\Users\Boštjan\Desktop\Chess Fighter\source\window.py", line 510, in mousePressEvent
    self.make_human_move(move)
  File "C:\Users\Boštjan\Desktop\Chess Fighter\source\window.py", line 578, in make_human_move
    game.truncate_to_current_move()
  File "C:\Users\Boštjan\Desktop\Chess Fighter\source\game.py", line 59, in truncate_to_current_move
    self.board.pop()
  File "C:\Program Files\Python 3.9\lib\site-packages\chess\__init__.py", line 2118, in pop
    move = self.move_stack.pop()
IndexError: pop from empty list
```

I don't understand how can the list be empty. @mfitzp?

**Comment by mfitzp** [comment]
The `move_stack` is managed on the game objects, and we're taking a copy of the game "state" (including the stack). That means it is no longer necessary to truncate the move stack (in the `truncate_to_current_move`).

That fixes the issue you saw, but there was a deeper problem here -- when stepping back to earlier moves, the earlier game object's move stack is continuing to be updated. This is because when returning previous states we weren't taking a copy of the board (again) -- that meant that play continued on the existing object, changing history.

```python
------ 6
historic stack 0: 1605563873864 [Move.from_uci('d2d3')]
historic stack 1: 1605563940168 [Move.from_uci('d2d3'), Move.from_uci('d7d5'), Move.from_uci('e2e3'), Move.from_uci('e7e5'), Move.from_uci('f2f3'), Move.from_uci('b8c6'), Move.from_uci('g2g3')]
historic stack 2: 1605563872712 [Move.from_uci('d2d3'), Move.from_uci('d7d5'), Move.from_uci('e2e3')]
historic stack 3: 1605563892104 [Move.from_uci('d2d3'), Move.from_uci('d7d5'), Move.from_uci('e2e3'), Move.from_uci('e7e5')]
historic stack 4: 1605563943496 [Move.from_uci('d2d3'), Move.from_uci('d7d5'), Move.from_uci('e2e3'), Move.from_uci('e7e5'), Move.from_uci('f2f3')]
historic stack 5: 1605563959112 [Move.from_uci('d2d3'), Move.from_uci('d7d5'), Move.from_uci('e2e3'), Move.from_uci('e7e5'), Move.from_uci('f2f3'), Move.from_uci('b8c6')]
historic stack 6: 1605563859208 [Move.from_uci('d2d3'), Move.from_uci('d7d5'), Move.from_uci('e2e3'), Move.from_uci('e7e5'), Move.from_uci('f2f3'), Move.from_uci('b8c6'), Move.from_uci('g2g3')]
```

Check the "fix" branch -- the first commit has the initial fix and some debug statements to produce the above output. The 2nd commit adds the copy when returning historic states. Seems to work now for me.

**Comment by PedanticHacker** [comment]
Yes, yes, yes! It now works flawlessly! Thank you very much, @mfitzp, for helping me out! 👍
