### ISSUE TITLE
Debugging with Python's PDB debugger

### ISSUE THREAD

**Issue by PedanticHacker** [PedanticHacker/ChessFighter#7]
![image](https://user-images.githubusercontent.com/14254085/93710862-021f9f80-fb4a-11ea-99af-2bd3ffff4643.png)

So I have determined why the chess engine crashes the application. The application crashes because the chess engine receives the wrong chessboard position. If you make moves **without** scrolling back to a historic chessboard position, the chess engine is happy and works perfectly fine (i.e., it doesn't crash). But if you play a new move in a historic chessboard position, the chess engine does not get the proper chessboard position.

Notice in the picture above that our code does not deal with the move stack properly. This is evident if you look at the selected move in the moves table and the position on the chessboard – the two do not match (whereas the arrow, however, is correct). The chessboard position that the chess engine receives (see PDB debugger printout in Command Prompt) is different that that on the SVG chessboard widget – different because the move `d4` should already be displayed (as indicated by the arrow) in the PDB debugger printout and also on the SVG chessboard widget. I think that the application crash arises because of this discrepancy.

I haven't determined where exactly should this issue be addressed, but I'm sure, @mfitzp, that we'll solve this together.

**Comment by mfitzp** [comment]
Hey @PedanticHacker  This was due to a missing truncation of the `self.history` object when truncating to earlier states. I had forgotten that this list was our own to manage, and not a property of the chess library itself. Because this wasn't truncated, the board and the move state would get out of sync + eventually there would be a move error.

You can trigger an error quicker by performing some moves, then truncating to a very early move twice -- the second time, the "moves to truncate" calculation will calculate a value longer than the move stack (because it uses `self.history` for the calculation) and throw an "pop from empty list" error.

This PR https://github.com/PedanticHacker/ChessFighter/pull/8 adds the truncate for history back in, and seems to work properly.

**Comment by PedanticHacker** [comment]
Thank you, thank you, thank you!
